// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhrl7M7aQ8s2xyyaXd-eAlKAjXpkEZByg',
    appId: '1:109078049167:web:cc43d3d15b230d842f1bfa',
    messagingSenderId: '109078049167',
    projectId: 'portfolio-22d86',
    authDomain: 'portfolio-22d86.firebaseapp.com',
    storageBucket: 'portfolio-22d86.appspot.com',
    measurementId: 'G-TMKJDHXETG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADCy3cSTzeqW6bVU47ZGkiESHtDVV8pIE',
    appId: '1:109078049167:android:84483c080932876f2f1bfa',
    messagingSenderId: '109078049167',
    projectId: 'portfolio-22d86',
    storageBucket: 'portfolio-22d86.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXLYhfJKN57AsSbNfVnd7qW4OZI7UlUTI',
    appId: '1:109078049167:ios:00ae6b17e8834ce42f1bfa',
    messagingSenderId: '109078049167',
    projectId: 'portfolio-22d86',
    storageBucket: 'portfolio-22d86.appspot.com',
    iosClientId: '109078049167-94i1qdim10nlvbh4mub39k8p27ejg7de.apps.googleusercontent.com',
    iosBundleId: 'com.jinnyportfolio.jinnyPortfolio',
  );
}
