// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArgxt2dKbWuPDGlGKf744VJ7NCKxb0H2U',
    appId: '1:479648066490:web:5966944e0ddd839653cb83',
    messagingSenderId: '479648066490',
    projectId: 'portfolio-b6949',
    authDomain: 'portfolio-b6949.firebaseapp.com',
    storageBucket: 'portfolio-b6949.appspot.com',
    measurementId: 'G-MMW39C8VKL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiZ_Ynpv8FkXyMUHD9BmqZac1TTm8lCiA',
    appId: '1:479648066490:android:998a58cade45105053cb83',
    messagingSenderId: '479648066490',
    projectId: 'portfolio-b6949',
    storageBucket: 'portfolio-b6949.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgcJj0_ic55QzpXi3z5C8sh5wKpRBlokg',
    appId: '1:479648066490:ios:aec54422cbeae1a453cb83',
    messagingSenderId: '479648066490',
    projectId: 'portfolio-b6949',
    storageBucket: 'portfolio-b6949.appspot.com',
    iosClientId: '479648066490-c0pha5fnihnotird3rsr3lh93jvv2oqr.apps.googleusercontent.com',
    iosBundleId: 'com.jinnyportfolio.jinnyPortfolio',
  );
}
